In [1]:
import numpy as np

In [4]:
print(*np.array([1,2,3]))

1 2 3


In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b+1+4/2


array([ 7., 13., 21.])

In [15]:
a=np.ones(33)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
a=np.array([[1,2,3],[2,4,6],[2,4,8]])
a

array([[1, 2, 3],
       [2, 4, 6],
       [2, 4, 8]])

In [23]:
b=np.array([[2,1,2],[4,6,8],[7,8,9]])

In [24]:
b

array([[2, 1, 2],
       [4, 6, 8],
       [7, 8, 9]])

In [25]:
a*b

array([[ 2,  2,  6],
       [ 8, 24, 48],
       [14, 32, 72]])

In [26]:
a+b-b*a

array([[  1,   1,  -1],
       [ -2, -14, -34],
       [ -5, -20, -55]])

In [30]:
c=(a+b)*(a-b)
c

array([[ -3,   3,   5],
       [-12, -20, -28],
       [-45, -48, -17]])

In [31]:
a**a

array([[       1,        4,       27],
       [       4,      256,    46656],
       [       4,      256, 16777216]])

In [32]:
a.ndim

2

In [34]:
a

array([[1, 2, 3],
       [2, 4, 6],
       [2, 4, 8]])

In [35]:
a.shape

(3, 3)

In [36]:
c=np.array([[2,1,2],[4,6,8]])

In [37]:
c.ndim

2

In [38]:
c.shape


(2, 3)

In [39]:
c


array([[2, 1, 2],
       [4, 6, 8]])

In [41]:
c.ndim

2

In [50]:
b=np.array([[2,1,2],[4,6,8],[7,8,9]],dtype='int64')

In [43]:
b.ndim

2

In [44]:
b

array([[2, 1, 2],
       [4, 6, 8],
       [7, 8, 9]])

In [45]:
b.dtype


dtype('int64')

In [47]:
b

array([[2, 1, 2],
       [4, 6, 8],
       [7, 8, 9]], dtype=int16)

In [48]:
b.dtype

dtype('int16')

In [52]:
b.itemsize


8

In [58]:
a.size

9

In [59]:
a.size *a.itemsize

72

In [61]:
a.nbytes

72

In [62]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [63]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [64]:
a.size

14

In [65]:
a[0,4]

5

In [68]:
a[1,4]

12

In [69]:
a[1:2]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [70]:
a[:4]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [71]:
a[::2]

array([[1, 2, 3, 4, 5, 6, 7]])

In [74]:
a[0,:2]

array([1, 2])

In [79]:
print(*a[:,4])

5 12


In [80]:
a[:,2]

array([ 3, 10])

In [81]:
a[1:4]=0
a

array([[1, 2, 3, 4, 5, 6, 7],
       [0, 0, 0, 0, 0, 0, 0]])

In [1]:
import numpy as np

In [2]:
b=np.array([[2,1,2],[4,6,8],[7,8,9]],dtype='int64')

In [4]:
b.dtype

dtype('int64')

In [15]:
b=np.array([[[2,1],[4,6]],[[7,8],[4,5]]])
b.ndim

3

In [16]:
b

array([[[2, 1],
        [4, 6]],

       [[7, 8],
        [4, 5]]])

In [11]:
b[0,1,1]

6

In [14]:
b[0,1,0]

4

In [29]:
a=np.ones((2,2,4,8))

In [30]:
a

array([[[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]]])

In [31]:
b=np.zeros((1,2))

In [32]:
b

array([[0., 0.]])

In [35]:
np.full((2,3,3,3),44)

array([[[[44, 44, 44],
         [44, 44, 44],
         [44, 44, 44]],

        [[44, 44, 44],
         [44, 44, 44],
         [44, 44, 44]],

        [[44, 44, 44],
         [44, 44, 44],
         [44, 44, 44]]],


       [[[44, 44, 44],
         [44, 44, 44],
         [44, 44, 44]],

        [[44, 44, 44],
         [44, 44, 44],
         [44, 44, 44]],

        [[44, 44, 44],
         [44, 44, 44],
         [44, 44, 44]]]])

In [39]:
np.full((4,4),12)


array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [40]:
b=np.array([[2,1,2],[4,6,8],[7,8,9]],dtype='int64')
b

array([[2, 1, 2],
       [4, 6, 8],
       [7, 8, 9]])

In [44]:
np.full_like(b,4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [45]:
b

array([[2, 1, 2],
       [4, 6, 8],
       [7, 8, 9]])

In [49]:
np.random.rand(2,3,4)

array([[[0.4958203 , 0.33582479, 0.33853611, 0.86433619],
        [0.19730024, 0.20300113, 0.17374578, 0.02880295],
        [0.22180996, 0.59816504, 0.48225254, 0.01215615]],

       [[0.4192266 , 0.4520316 , 0.90244403, 0.41821684],
        [0.58354371, 0.90456975, 0.75597101, 0.91257947],
        [0.70220685, 0.23649919, 0.21998585, 0.94425732]]])

In [2]:
np.random.random_sample(b.shape)

import numpy as np


NameError: name 'np' is not defined

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [16]:
a = np.random.randint(5,7,size=(3,3))

In [19]:
a

array([[5, 5, 5],
       [6, 6, 5],
       [6, 5, 5]])

In [21]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
import numpy as np
arr=([[1,2,3]])
a=np.repeat(arr,3,axis=0)

In [5]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
a*2+5

array([[ 7,  9, 11],
       [ 7,  9, 11],
       [ 7,  9, 11]])

In [8]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
import numpy as np

In [13]:
a=np.ones((5,5))

In [14]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
z=np.zeros((3,3))
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [23]:
a[1:4,1:4]=z
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
a=([1,2,3])
a

[1, 2, 3]

In [27]:
b=a
b
b[0]=100
b

[100, 2, 3]

In [31]:
a=np.array([1,2,3])

b=a.copy()

b[0]=100
b

array([100,   2,   3])

In [35]:
a=np.random.randint((3,3,3))
a

array([2, 2, 2])

In [38]:
a=np.array([2, 2, 2])

np.tan(a)

array([-2.18503986, -2.18503986, -2.18503986])

In [45]:
a=np.ones((3,2))
print(a)
b=np.full((2,3),2)
b
c=np.matmul(a,b)
c

[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [46]:
c

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [47]:
b

array([[2, 2, 2],
       [2, 2, 2]])

In [51]:
c=np.identity(4)
c1=np.linalg.det(c)
c1

1.0

In [55]:
c=([[1,2,3],[2,4,6],[1,0,0]])
x=np.linalg.det(c)
x

0.0

In [1]:
import numpy as np

In [12]:
stats=np.array([[[1,2,3]],[[2,4,5]]])

In [13]:
stats

array([[[1, 2, 3]],

       [[2, 4, 5]]])

In [6]:
np.min(stats)

1

In [7]:
np.max(stats
      )

5

In [16]:
np.min(stats,axis=0)

array([[1, 2, 3]])

In [17]:
np.sum(stats)

17

In [36]:
before=np.array([[1,2,3],[4,8,6]])
before.shape

after=before.reshape((6,1))
after

array([[1],
       [2],
       [3],
       [4],
       [8],
       [6]])

In [43]:
a=np.array([1,4,5])
b=np.array([8,6,9])
c=np.array([7,6,8])
print(d/2)
d=np.vstack([a,b,c**c])
d

[[5.000000e-01 2.000000e+00 2.500000e+00]
 [4.000000e+00 3.000000e+00 4.500000e+00]
 [4.117715e+05 2.332800e+04 8.388608e+06]]


array([[       1,        4,        5],
       [       8,        6,        9],
       [  823543,    46656, 16777216]])

In [52]:
g=np.ones((2,4))
j=np.identity(2)

In [45]:
g

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
j

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
v=np.hstack((g,j))
v/2*np.ones((2,6))+1


array([[1.5, 1.5, 1.5, 1.5, 1.5, 1. ],
       [1.5, 1.5, 1.5, 1.5, 1. , 1.5]])

In [63]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[4,8,2]]

array([5, 9, 3])