In [1]:
print(5)

5


In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
import numpy

In [1]:
print("hey numps")


hey numps


In [1]:
def apply():
    print("hey you got a message")
    
print("start")
apply()
print("finish")
    

start
hey you got a message
finish


In [3]:

from array import array

value=array('i',[1,2,3,4,5,6])
print(value)

array('i', [1, 2, 3, 4, 5, 6])


In [11]:

from array import array

value=array('i',[1,2,3,4,5,6,1,2,3,4,5,6])
print(value)

array('i', [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])


In [13]:
from numpy import array
spec=([1,2,3])
print(spec)

[1, 2, 3]


In [14]:
from numpy import array
spec=([1,2,3],=([4,5,6],[7,8,9])
print(spec)

([1, 2, 3], [4, 5, 6], [7, 8, 9])


In [4]:
import numpy as np


In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
print(a)


[1 2 3]


In [8]:
b=np.array([2,3,4])
c=np.array([6,7,8],dtype='int16')
print(b,c)
b,c



[2 3 4] [6 7 8]


(array([2, 3, 4]), array([6, 7, 8]))

In [9]:
b*c

array([12, 21, 32])

In [10]:
a.ndim

1

In [14]:
c.ndim

1

In [12]:
c.ndim

1

In [13]:
b.ndim

1

In [15]:
c.shape


(3,)

In [16]:
b.shape

(3,)

In [17]:
a.shape

(3,)

In [18]:
a.dtype

dtype('int64')

In [ ]:
b=np.array([2,3])
c=np.array([6,7,8],dtype='int16')
print(b,c)
b,c


In [19]:
c.dtype

dtype('int64')

In [23]:
c.size

3

In [27]:
c.itemsize

8

In [28]:
c.itemsize

8

In [29]:
a.itemsize

8

In [32]:
b.size

3

In [31]:
c.size

3

In [33]:
b.size

3

In [37]:
b=np.array([2,3,6])
b

array([2, 3, 6])

In [35]:
b.size

2

In [36]:
b.nbytes

16

In [38]:
b.nbytes

24

In [49]:
a=np.array([[1,2,3,4,5,6,78],[9,10,11,12,13,14]])
print(a)

[list([1, 2, 3, 4, 5, 6, 78]) list([9, 10, 11, 12, 13, 14])]


/tmp/ipykernel_4107/39721783.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3,4,5,6,78],[9,10,11,12,13,14]])


In [50]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [51]:
a=np.array([[1,2,3,4,5,6,78],[9,10,11,12,13,14]])
print(a)

[list([1, 2, 3, 4, 5, 6, 78]) list([9, 10, 11, 12, 13, 14])]


/tmp/ipykernel_4107/39721783.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3,4,5,6,78],[9,10,11,12,13,14]])


In [52]:
a=np.array([])
a

array([], dtype=float64)

In [53]:
a

array([], dtype=float64)

In [54]:
a=0

In [55]:
a

0

In [56]:


a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [58]:
a = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(a)

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]


In [60]:
a[-1,2]

3

In [61]:
a.shape

(2, 7)

In [62]:
a.size

14

In [63]:
a.itemsize

8

In [64]:
a[0::]

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [65]:
a[0:]

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [66]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
a[0,::]

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
np.zeros((1,2,4,9))

array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])

In [77]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [81]:
np.ones((2,4,4,10))

array([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1.,

In [82]:
##value assignining to the array

np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [83]:
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [85]:
np.random.rand(4,2)

array([[0.29416487, 0.63070213],
       [0.31906094, 0.39910852],
       [0.32482402, 0.79192912],
       [0.92508866, 0.43533647]])

In [87]:
np.random.rand(2,4,3)

array([[[0.55275633, 0.62553837, 0.3041005 ],
        [0.7982217 , 0.26403407, 0.60450422],
        [0.08738621, 0.6960993 , 0.37033385],
        [0.2607462 , 0.45519707, 0.93424426]],

       [[0.95914777, 0.98348238, 0.10176276],
        [0.52641502, 0.74957672, 0.84984308],
        [0.71232175, 0.35389344, 0.52469519],
        [0.20263015, 0.32607206, 0.67604821]]])

In [97]:
np.random.randint(2,8,size=(2,2))

array([[2, 3],
       [2, 5]])

In [101]:
np.random.randint(2,100,size=(10,10))

array([[ 3, 20, 61, 82, 89,  8, 77, 69,  6, 25],
       [41, 57, 23, 74, 37, 18, 53, 28, 45, 63],
       [19, 56, 95, 65, 40,  4, 54, 61, 91, 44],
       [21, 89, 57, 44, 31,  9, 83, 35, 64, 84],
       [22, 24, 75, 63, 20, 67, 83, 57, 19,  2],
       [95, 57, 90, 46, 15, 50, 45, 76, 48, 82],
       [19,  8, 84, 50, 97, 73, 73, 68, 84, 78],
       [68, 57, 66, 51, 58, 86, 41, 32, 40, 88],
       [55, 92,  9, 90, 91, 39, 53, 14, 49, 59],
       [66, 95, 99, 21, 42, 82, 43,  6, 18, 96]])

In [102]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
np.identity(99)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [105]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [2]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

NameError: name 'np' is not defined

In [3]:
specs=np.array([[[1,2,3]]])
f=np.repeat(specs,4,axis=1)
print(f)

NameError: name 'np' is not defined

In [127]:
#printing unique matrix like

output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)

z[1,1]=9
print(z)
 
output[1:4,1:4]=z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
import numpy as np


In [6]:
specs=np.array([[[1,2,3]]])
f=np.repeat(specs,4,axis=1)
print(f)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]


In [11]:
import numpy as np

In [15]:
a = np.array([[[1,2,3]]])
s=np.repeat(a,3,axis=1)
print(s)


[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [21]:
a =  np.array([1,2,3])
b=a.copy()
b[0] = 100
print(a)

[1 2 3]


In [22]:
a =  np.array([1,2,3])
b=a
b[0] = 100
print(a)

[100   2   3]


In [23]:
a = np.array([1,2,3,4])
b=np.array([1,0,1,0])
a
b


array([1, 0, 1, 0])

In [24]:
a+2

array([3, 4, 5, 6])

In [25]:
a*2

array([2, 4, 6, 8])

In [26]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [27]:
a+b

array([2, 2, 4, 4])

In [28]:
a*b

array([1, 0, 3, 0])

In [29]:
a-b

array([0, 2, 2, 4])

In [35]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
a = np.array([1,2,3,4])
b=np.array([1,0,1,0])

In [37]:
a*2


array([2, 4, 6, 8])

In [38]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [40]:
np.tan(a+b)

array([-2.18503986, -2.18503986,  1.15782128,  1.15782128])

In [50]:
a = np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

c = np.matmul(a,b)
print(c)




[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [51]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [52]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
##find the determinent
c = np.identity(10)
np.linalg.det(c)


1.0

In [59]:
a=np.identity(5)
print(a)

np.linalg.det(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


1.0

statistics

In [64]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

1

In [69]:
np.max(stats)

6

In [70]:
np.min(stats,axis=1)

array([1, 4])

In [71]:
np.max(stats,axis=1)

array([3, 6])

In [72]:
np.sum(stats)

21

In [73]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [74]:
np.sum(stats,axis=1)

array([ 6, 15])

reorganising arrays

In [80]:
before = np.array([[1,2,3,4],[4,5,6,4]])
print(before.shape)

after = before.reshape(8,1)
print(after)


(2, 4)
[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [6]
 [4]]


In [89]:
before = np.array([[1,2,3,4],[4,5,6,4]])
print(before.shape)

after = before.reshape(2,4)
print(after)

(2, 4)
[[1 2 3 4]
 [4 5 6 4]]


In [92]:
##vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([8,9,6,4])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [8, 9, 6, 4],
       [1, 2, 3, 4],
       [8, 9, 6, 4]])

In [96]:
##horizotal stack

h=np.ones((2,4))
q=np.zeros((2,2))
z=np.hstack((h,q))
print(z)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
